src/Entity/Lesson.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LessonRepository")
 */
class Lesson
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="lessons")
     */
    private $teacher;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Subject", inversedBy="lessons")
     */
    private $subject;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="date")
     */
    private $start_date;

    /**
     * @ORM\Column(type="date")
     */
    private $end_date;

    /**
     * @ORM\Column(type="time")
     */
    private $start_time;

    /**
     * @ORM\Column(type="time")
     */
    private $end_time;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Grade", inversedBy="lessons")
     */
    private $grade;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTeacher(): ?User
    {
        return $this->teacher;
    }

    public function setTeacher(?User $teacher): self
    {
        $this->teacher = $teacher;

        return $this;
    }

    public function getSubject(): ?Subject
    {
        return $this->subject;
    }

    public function setSubject(?Subject $subject): self
    {
        $this->subject = $subject;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getStartTime(): ?\DateTimeInterface
    {
        return $this->start_time;
    }

    public function setStartTime(\DateTimeInterface $start_time): self
    {
        $this->start_time = $start_time;

        return $this;
    }

    public function getEndTime(): ?\DateTimeInterface
    {
        return $this->end_time;
    }

    public function setEndTime(\DateTimeInterface $end_time): self
    {
        $this->end_time = $end_time;

        return $this;
    }

    public function getGrade(): ?Grade
    {
        return $this->grade;
    }

    public function setGrade(?Grade $grade): self
    {
        $this->grade = $grade;

        return $this;
    }

    public function __toString()
    {
        return $this->subject.' - '.$this->start_date->format('d/m/Y').' at '.$this->start_time->format('H:i');
    }
}

templates/pages/account.twig
{% extends 'layouts/page.twig' %}

{% block body %}
    <div class="container pt-8">
        <h1 class="mb-4 large-title">
            Account
        </h1>

        <div class="flex flex-wrap">
            <div class="w-full mb-4 md:w-1/4 md:mb-0 text-sm">
                <div class="font-semibold">Security</div>
            </div>

            <div class="w-full md:w-3/4">
                <form class="p-6 border border-gray-200 rounded"
                      method="POST">
                    <div class="text-xl font-semibold tracking-tight mb-4">Change Password</div>

                    {% if errors is defined %}
                        {% for error in errors %}
                            <div class="text-xs text-red-600 mb-2">{{ error }}</div>
                        {% endfor %}
                    {% elseif success is defined %}
                        <div class="text-xs text-green-600 mb-2">{{ success }}</div>
                    {% endif %}

                    <div class="max-w-sm mb-8">
                        <input
                            class="form-control mb-8"
                            name="current_password"
                            placeholder="Your current password"
                            required
                            type="password"
                        >

                        <input
                            class="form-control mb-4"
                            name="new_password"
                            placeholder="Your new password"
                            required
                            type="password"
                        >
                        <input
                            class="form-control"
                            name="new_password_confirmation"
                            placeholder="Confirm new password"
                            required
                            type="password"
                        >
                    </div>

                    <button class="btn btn-black"
                            type="submit">
                        Save
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/home.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container pt-8">
        <h1>Home</h1>
    </div>
{% endblock %}

templates/pages/home.twig
{% extends 'layouts/page.twig' %}

{% block body %}
    <div class="container pt-8">
        <h1 class="large-title font-bold mb-4">
            Welcome {{ app.user.firstName }}
        </h1>
    </div>
{% endblock %}

templates/pages/login.twig
{% extends 'layouts/page.twig' %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <div class="w-64 mx-auto mt-8">
        <form class="w-full max-w-sm" method="post">
            <h1 class="text-3xl font-bold tracking-tight mb-4">Log in to Studiary</h1>

            {% if error %}
                <div class="text-xs text-red-600 mb-4">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
            {% endif %}

            <div class="mb-8">
                <label class="block form-label"
                       for="inputEmail">
                    Email
                </label>
                <input
                    id="inputEmail"
                    autofocus
                    class="form-control"
                    name="email"
                    placeholder="johndoe@mail.com"
                    required
                    type="email"
                    value="{{ last_username }}"
                >
            </div>

            <div class="mb-8">
                <label class="block form-label"
                       for="inputPassword">
                    Password
                </label>
                <input
                    id="inputPassword"
                    class="form-control"
                    name="password"
                    placeholder="********"
                    required
                    type="password"
                >
            </div>

            <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">

            {#
            Uncomment this section and add a remember_me option below your firewall to activate remember me functionality.
            See https://symfony.com/doc/current/security/remember_me.html

            <div class="checkbox mb-3">
                <label>
                    <input type="checkbox" name="_remember_me"> Remember me
                </label>
            </div>
            #}
            <button class="btn btn-black block ml-auto"
                    type="submit">
                Log in
            </button>
        </form>
    </div>
{% endblock %}

templates/pages/student_home.twig
{% extends 'layouts/page.twig' %}

{% block body %}
    <div class="container pt-8">
        <h1 class="large-title font-bold mb-4">
            Welcome {{ app.user.firstName }}
        </h1>

        <div class="grid md:grid-cols-2 gap-8 text-sm">
            <div>
                <h2 class="mb-3 text-lg font-semibold">Your next lessons</h2>

                {% if lessons %}
                    <div class="text-sm">
                        {% for lesson in lessons %}
                            <div>
                                <div class="px-2 py-1 font-semibold bg-gray-200 rounded">
                                    {{ lesson.startDate | date('D j M', timezone="Europe/Paris") }}
                                </div>

                                <div class="flex items-center">
                                    <div class="pl-4 pr-2 py-1 text-xs text-right">
                                        <div>{{ lesson.startTime | date('H:i', timezone="Europe/Paris") }}</div>
                                        <div>{{ lesson.endTime | date('H:i', timezone="Europe/Paris") }}</div>
                                    </div>

                                    <div class="py-1 px-2 truncate">
                                        <div class="text-base truncate">{{ lesson.subject }}</div>
                                        <div class="text-xs text-gray-600 truncate">{{ lesson.name }}</div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    No more lessons!
                {% endif %}
            </div>

            <div>
                <div class="mb-3 flex justify-between align-center">
                    <h2 class=" text-lg font-semibold inline">Your last notes</h2>

                    <a href="/notes" class="float-right text-gray-600 self-center">See all</a>
                </div>

                {% if notes %}
                    <div>
                        {% for note in notes %}
                            <div class="flex mb-2">
                                <div class="flex-grow">
                                    <div>{{ note.subject }}</div>
                                    <div class="text-xs text-gray-600">
                                        {{ note.date | date('D j M', timezone="Europe/Paris") }}
                                    </div>
                                </div>
                                <div>{{ note.value }}</div>
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    No notes for now.
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/student_note.twig
{% extends 'layouts/page.twig' %}

{% block body %}
    <div class="container pt-8">
        <h1 class="mb-4 text-4xl font-semibold tracking-tight leading-tight">Notes</h1>

        {% if notes %}
            <div>
                {% for note in notes %}
                    <div class="flex mb-2 border-b pb-3">
                        <div class="flex-grow">
                            <div>{{ note.subject }}</div>
                            <div class="text-xs text-gray-600">
                                {{ note.date | date('D j M', timezone="Europe/Paris") }}
                            </div>
                        </div>
                        <div>{{ note.value }}</div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            No notes for now.
        {% endif %}
        

    </div>
{% endblock %}

templates/pages/teacher_home.twig
{% extends 'layouts/page.twig' %}

{% block body %}
    <div class="container pt-8">
        <h1 class="large-title font-bold mb-4">
            Welcome {{ app.user.firstName }}
        </h1>

        <div>
            <h2 class="mb-3 text-lg font-semibold">Your next lessons</h2>

            {% if lessons %}
                <div class="max-w-lg text-sm">
                    {% for lesson in lessons %}
                        <div>
                            <div class="py-1 px-2 font-semibold bg-gray-200 rounded">
                                {{ lesson.startDate | date('D j M') }}
                            </div>

                            <div class="flex items-center">
                                <div class="py-1 pl-4 pr-2 text-xs text-right">
                                    <div>{{ lesson.startTime | date('H:i') }}</div>
                                    <div>{{ lesson.endTime | date('H:i') }}</div>
                                </div>

                                <div class="py-1 px-2 truncate">
                                    <div class="text-base truncate">{{ lesson.subject }}</div>
                                    <div class="text-xs text-gray-600 truncate">{{ lesson.name }}</div>
                                </div>

                                <div class="py-1 pl-4 truncate">
                                    {{ lesson.grade }}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                No more lessons!
            {% endif %}
        </div>
    </div>
{% endblock %}